# Site settings
title: I'm Erik King-Vargas!
description: A portfolio site for Erik King-Vargas
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Erik King-Vargas
user_title: 
user_job_title: Data Scientist
email: erik.king.vargas [at] gmail.com
# twitter_username: 
github_username:  erikvvargas

exclude: ['package.json', 'src' , 'node_modules']
